### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by SomeWarez** [IndeedMiners/PolarisBiosEditor#5]
Clicking the One Click Timing Patch button without loading a ROM will give this error.

Unhandled exception - InvalidArgument=Value of '1' is not valid for 'index'

System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at PolarisBiosEditor.PolarisBiosEditor.button1_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by IndeedMiners** [comment]
Right, the button is deactivated only in PRO version. I will do the same changes in here too.
